FROM centos:6

RUN sed -e 's/mirror\.centos\.org/vault\.centos\.org/g' \
        -e 's/^mirrorlist=/#mirrorlist=/g' \
        -e 's/^#\s*baseurl=/baseurl=/g' \
        -i /etc/yum.repos.d/CentOS-*.repo \
  && yum install -y @development bzip2 ca-certificates texinfo wget zlib-devel \
  # Need newer GCC and GAS (binutils) to build with CET support
  && yum install -y centos-release-scl-rh \
  && sed -e 's/mirror\.centos\.org/vault\.centos\.org/g' \
         -e 's/^mirrorlist=/#mirrorlist=/g' \
         -e 's/^#\s*baseurl=/baseurl=/g' \
         -i /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo \
  && yum install -y devtoolset-9-gcc devtoolset-9-gcc-c++ devtoolset-9-binutils \
  && yum clean all

RUN useradd --create-home --shell /bin/bash linuxbrew

ENV PATH=/opt/rh/devtoolset-9/root/usr/bin:${PATH}
ENV CFLAGS="-march=core2 -O2"
ENV CXXFLAGS="-march=core2 -O2"
ENV PREFIX=/tmp/homebrew
RUN su - linuxbrew --command 'mkdir --parents /tmp/homebrew'
ENV PKGDIR=/home/linuxbrew/bootstrap-binaries
RUN su - linuxbrew --command 'mkdir --parents /home/linuxbrew/bootstrap-binaries'
